### ISSUE TITLE
Mockup Screen

### ISSUE THREAD

**Issue by levidasilvalima** [m1ojo/miojo#3] opened 2019-07-15 04:08 UTC
Begin mockup project of user profile, dashboard, login

**Comment by Diegovisk** [comment] 2019-07-16 05:53
@levidasilvalima be aware that this is a duplicate of [#2](https://github.com/m1ojo/miojo-app/issues/2) in the correct repo: miojo-app. :)

**Closed as completed** 2019-07-16 05:53 UTC
Labels: duplicate

**Comment by RodrigoCMoraes** [comment] 2019-07-16 13:37
@Mozz4rt is a good idea tell what is the original issue when telling that one is duplicated.
